services:
  web:
    image: uw-comms:${UW_COMMS_VERSION:-latest}
    container_name: uw-comms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${UW_COMMS_PORT:-8080}:8080'
    restart: unless-stopped
